import { Boxes, CheckCircle2, XCircle } from "lucide-react";
import { getReadiness, getSystemInfo } from "../api/endpoints";
import TopBar from "../components/layout/TopBar";
import { AsyncSection } from "../components/ui/AsyncState";
import StatusPill from "../components/ui/StatusPill";
import { useApiResource } from "../hooks/useApiResource";

export default function IntegrationsPage() {
  const system = useApiResource(({ signal }) => getSystemInfo({ signal }), []);
  const readiness = useApiResource(({ signal }) => getReadiness({ signal }), []);
  const components = system.data?.enabledComponents ?? [];
  const checks = readiness.data?.checks ?? readiness.data?.dependencies ?? {};
  return <div className="flex flex-col flex-1"><TopBar breadcrumbs={["Platform", "Integrations"]} /><main className="flex-1 overflow-y-auto p-6 space-y-5"><div><h1 className="text-xl font-bold text-gray-900">Backend Integrations</h1><p className="text-sm text-gray-500 mt-1">Components and dependencies reported by the running API.</p></div><AsyncSection {...system} onRetry={system.refetch}><div className="grid grid-cols-1 lg:grid-cols-2 gap-5"><section className="bg-white border border-gray-200 rounded-xl shadow-sm p-5"><div className="flex items-center gap-2 mb-4"><Boxes size={16} className="text-blue-500" /><h2 className="text-sm font-bold text-gray-900">Enabled components</h2></div>{components.length ? <ul className="space-y-2">{components.map((component) => <li key={component} className="flex items-center gap-2 border border-gray-100 rounded-lg px-3 py-2 text-sm text-gray-700"><CheckCircle2 size={14} className="text-green-500" />{component}</li>)}</ul> : <p className="text-sm text-gray-500">No optional components are enabled.</p>}</section><section className="bg-white border border-gray-200 rounded-xl shadow-sm p-5"><div className="flex items-center justify-between mb-4"><h2 className="text-sm font-bold text-gray-900">Dependency readiness</h2><StatusPill status={readiness.data?.status ?? (readiness.error ? "UNHEALTHY" : "CHECKING")} /></div>{readiness.error && !readiness.data ? <button className="text-xs font-semibold text-blue-600" onClick={readiness.refetch}>Retry readiness check</button> : Object.keys(checks).length ? <ul className="space-y-2">{Object.entries(checks).map(([name, check]) => { const healthy = check === true || check === "ok" || check?.status === "healthy" || check?.status === "up"; return <li key={name} className="flex items-center gap-2 border border-gray-100 rounded-lg px-3 py-2 text-sm"><span className="capitalize flex-1 text-gray-700">{name}</span>{healthy ? <CheckCircle2 size={14} className="text-green-500" /> : <XCircle size={14} className="text-red-400" />}</li>; })}</ul> : <p className="text-sm text-gray-500">No individual dependency checks were returned.</p>}</section></div></AsyncSection></main></div>;
}
