import {useRef,useState} from "react";
import {Activity,CheckCircle2,FileJson,FileText,FileUp,MessageSquareText,RefreshCw,Send,Trash2,X,XCircle} from "lucide-react";
import TopBar from "../components/layout/TopBar";
import StatusPill from "../components/ui/StatusPill";
import {useProject} from "../context/useProject";
import {useApiResource} from "../hooks/useApiResource";
import {deleteClusterEndUser,getClusterSmsAgent,importClusterEndUsers,requestClusterSmsTest} from "../api/endpoints";

export default function SmsAgentPage(){
  const {activeProject}=useProject(),clusterId=activeProject?.id;
  const resource=useApiResource(({signal})=>getClusterSmsAgent(clusterId,{signal}),[clusterId],{enabled:Boolean(clusterId),pollMs:15000});
  const input=useRef(null);const[busy,setBusy]=useState(false),[notice,setNotice]=useState(null),[consent,setConsent]=useState(false),[showImport,setShowImport]=useState(false),[format,setFormat]=useState(null),[jsonText,setJsonText]=useState("");
  const submitFile=async file=>{if(!file)return;setBusy(true);setNotice(null);try{const result=await importClusterEndUsers(clusterId,file,consent);setNotice({ok:result.rejected===0,text:`Imported ${result.imported} contact${result.imported===1?"":"s"}.${result.rejected?` ${result.rejected} rejected: ${result.errors.join("; ")}`:""}`});await resource.refetch();setShowImport(false);setFormat(null);setJsonText("");}catch(error){setNotice({ok:false,text:error.message||"Import failed."});}finally{setBusy(false);if(input.current)input.current.value="";}};
  const upload=event=>void submitFile(event.target.files?.[0]);
  const chooseFile=kind=>{setFormat(kind);if(consent)setTimeout(()=>input.current?.click(),0);};
  const submitJson=()=>{try{JSON.parse(jsonText);}catch{setNotice({ok:false,text:"The pasted value is not valid JSON."});return;}void submitFile(new File([jsonText],"contacts.json",{type:"application/json"}));};
  const test=async()=>{setBusy(true);setNotice(null);try{const result=await requestClusterSmsTest(clusterId);setNotice({ok:true,text:`Test SMS queued for ${result.recipient}.`});setTimeout(()=>void resource.refetch(),1000);}catch(error){setNotice({ok:false,text:error.message||"Could not queue test SMS."});}finally{setBusy(false);}};
  const remove=async contact=>{if(!window.confirm(`Remove ${contact.name} from this cluster?`))return;setBusy(true);try{await deleteClusterEndUser(clusterId,contact.id);await resource.refetch();}catch(error){setNotice({ok:false,text:error.message||"Could not remove contact."});}finally{setBusy(false);}};
  if(!clusterId)return <div className="p-8 text-sm text-gray-600">Open an onboarded cluster before managing its SMS recipients.</div>;
  const data=resource.data,status=data?.status,contacts=data?.contacts??[],deliveries=data?.deliveries??[];
  return <div className="flex flex-1 flex-col"><TopBar breadcrumbs={[activeProject.name,"SMS Agent"]}/><main className="flex-1 space-y-5 overflow-y-auto p-6">
    <div className="flex flex-wrap items-start justify-between gap-3"><div><h1 className="text-xl font-bold text-gray-900">SMS Agent</h1><p className="mt-1 text-sm text-gray-500">Cluster-scoped end users receive critical outage, restoration-time, and recovery updates.</p></div><div className="flex gap-2"><button onClick={()=>{setConsent(false);setShowImport(true);}} disabled={busy} className="inline-flex items-center gap-2 rounded-lg border border-gray-200 bg-white px-4 py-2 text-sm font-semibold disabled:text-gray-300"><FileUp size={16}/>Upload contacts</button><button onClick={test} disabled={busy||!status?.connected||!status?.smsAgentConfigured||!contacts.length} className="inline-flex items-center gap-2 rounded-lg bg-blue-600 px-4 py-2 text-sm font-semibold text-white disabled:bg-gray-300"><Send size={16}/>Test SMS</button><input ref={input} type="file" accept={format==="pdf"?".pdf,application/pdf":".csv,text/csv"} className="hidden" onChange={upload}/></div></div>
    {notice&&<div className={`rounded-lg border px-4 py-3 text-sm ${notice.ok?"border-green-200 bg-green-50 text-green-800":"border-red-200 bg-red-50 text-red-700"}`}>{notice.text}</div>}
    {resource.error&&<div className="rounded-lg border border-red-200 bg-red-50 p-4 text-sm text-red-700">{resource.error.message}<button className="ml-3 underline" onClick={resource.refetch}>Retry</button></div>}
    <section className="rounded-xl border border-gray-200 bg-white shadow-sm"><div className="flex items-center gap-2 border-b px-5 py-4"><Activity size={16}/><h2 className="text-sm font-bold">Configuration Status</h2><button type="button" aria-label="Refresh SMS configuration status" title="Refresh configuration status" disabled={resource.refreshing} className="ml-auto text-gray-400 hover:text-blue-600 disabled:cursor-wait" onClick={resource.refetch}><RefreshCw size={15} className={resource.refreshing?"animate-spin":""}/></button></div><div className="grid gap-4 p-5 md:grid-cols-3"><Health label="Retell connection" healthy={status?.connected} detail={status?.message||"Not reported"}/><Health label="SMS agent" healthy={!status?.stale&&status?.smsAgentConfigured} detail={status?.stale?"Worker status is stale":status?.smsAgentConfigured?"Configured":"Not configured"}/><Health label="Cluster recipients" healthy={contacts.length>0} detail={`${contacts.length} uploaded`}/></div>{status?.checkedAt&&<p className="px-5 pb-4 text-xs text-gray-400">Last checked {new Date(status.checkedAt).toLocaleString()}. Configuration changes require a notification-service restart.</p>}</section>
    <section className="overflow-hidden rounded-xl border border-gray-200 bg-white shadow-sm"><div className="border-b px-5 py-4"><h2 className="text-sm font-bold">End users</h2><p className="mt-1 text-xs text-gray-500">Accepted header: <code>name,email,contact,service</code>. Contact must use E.164 format; use service <code>*</code> for every service in this cluster.</p></div><Table headers={["Name","Email","Contact","Service",""]} empty="No end users uploaded.">{contacts.map(item=><tr key={item.id} className="border-t"><td className="px-5 py-3 font-semibold">{item.name}</td><td className="px-5 py-3 text-gray-600">{item.email}</td><td className="px-5 py-3 font-mono text-gray-600">{mask(item.phoneNumber)}</td><td className="px-5 py-3">{item.service}</td><td className="px-5 py-3 text-right"><button aria-label={`Remove ${item.name}`} onClick={()=>remove(item)} className="text-gray-400 hover:text-red-600"><Trash2 size={15}/></button></td></tr>)}</Table></section>
    <section className="overflow-hidden rounded-xl border border-gray-200 bg-white shadow-sm"><div className="flex items-center gap-2 border-b px-5 py-4"><MessageSquareText size={16}/><h2 className="text-sm font-bold">Recent SMS deliveries</h2></div><Table headers={["Incident","Recipient","Type","Status","Time"]} empty="No SMS deliveries yet.">{deliveries.map(item=>{const contact=contacts.find(value=>value.id===item.recipientId);return <tr key={item.id} className="border-t"><td className="px-5 py-3 font-mono text-xs">{item.communicationType==="TEST"?"Test":item.incidentId}</td><td className="px-5 py-3">{contact?.name||"Removed contact"}</td><td className="px-5 py-3 text-gray-600">{item.communicationType.replaceAll("_"," ")}</td><td className="px-5 py-3"><StatusPill status={item.status}/></td><td className="px-5 py-3 text-gray-500">{new Date(item.sentAt||item.createdAt).toLocaleString()}</td></tr>;})}</Table></section>
    {showImport&&<ImportDialog format={format} jsonText={jsonText} consent={consent} busy={busy} onFormat={setFormat} onJson={setJsonText} onConsent={setConsent} onChooseFile={chooseFile} onSubmitJson={submitJson} onClose={()=>{if(!busy){setShowImport(false);setFormat(null);}}}/>}
  </main></div>;
}
function ImportDialog({format,jsonText,consent,busy,onFormat,onJson,onConsent,onChooseFile,onSubmitJson,onClose}){return <div className="fixed inset-0 z-50 flex items-center justify-center bg-gray-950/40 p-4" role="dialog" aria-modal="true" aria-labelledby="import-title"><div className="w-full max-w-xl rounded-2xl bg-white shadow-xl"><div className="flex items-start border-b border-gray-100 px-5 py-4"><div><h2 id="import-title" className="font-bold text-gray-900">Import end users</h2><p className="mt-1 text-xs text-gray-500">Choose a file format or paste JSON directly.</p></div><button onClick={onClose} disabled={busy} aria-label="Close import dialog" className="ml-auto text-gray-400 hover:text-gray-700"><X size={18}/></button></div><div className="space-y-4 p-5"><label className="flex items-start gap-2 rounded-lg border border-amber-200 bg-amber-50 px-3 py-2 text-xs text-amber-900"><input type="checkbox" checked={consent} onChange={event=>onConsent(event.target.checked)} className="mt-0.5"/><span>I confirm every imported recipient opted in to service-status SMS.</span></label><div className="grid grid-cols-3 gap-3"><FormatButton active={format==="csv"} icon={FileText} label="CSV file" onClick={()=>onChooseFile("csv")}/><FormatButton active={format==="pdf"} icon={FileText} label="PDF file" onClick={()=>onChooseFile("pdf")}/><FormatButton active={format==="json"} icon={FileJson} label="Paste JSON" onClick={()=>onFormat("json")}/></div>{format==="json"&&<div><label className="mb-1.5 block text-xs font-semibold text-gray-700" htmlFor="contacts-json">JSON contacts</label><textarea id="contacts-json" rows={10} value={jsonText} onChange={event=>onJson(event.target.value)} placeholder={'[\n  {"name":"Ada","email":"ada@example.com","contact":"+15551234567","service":"payments"}\n]'} className="w-full rounded-lg border border-gray-200 p-3 font-mono text-xs outline-none focus:border-blue-500"/><button onClick={onSubmitJson} disabled={busy||!consent||!jsonText.trim()} className="mt-3 w-full rounded-lg bg-blue-600 px-4 py-2 text-sm font-semibold text-white disabled:bg-gray-300">{busy?"Importing…":"Import JSON"}</button></div>}{!consent&&<p className="rounded-lg bg-amber-50 px-3 py-2 text-xs text-amber-800">Confirm recipient consent before importing.</p>}<p className="text-xs text-gray-500">Required fields: <code>name</code>, <code>email</code>, <code>contact</code>, and <code>service</code>. PDF files must contain extractable text.</p></div></div></div>;}
function FormatButton({active,icon:Icon,label,onClick}){return <button type="button" onClick={onClick} className={`flex flex-col items-center gap-2 rounded-xl border p-4 text-sm font-semibold ${active?"border-blue-500 bg-blue-50 text-blue-700":"border-gray-200 text-gray-600 hover:bg-gray-50"}`}><Icon size={22}/>{label}</button>;}
function Health({label,healthy,detail}){const Icon=healthy?CheckCircle2:XCircle;return <div className={`rounded-lg border p-4 ${healthy?"border-green-200 bg-green-50":"border-amber-200 bg-amber-50"}`}><div className="flex items-center gap-2"><Icon size={17} className={healthy?"text-green-600":"text-amber-600"}/><p className="text-xs font-bold uppercase text-gray-600">{label}</p></div><p className="mt-2 text-sm font-semibold">{detail}</p></div>;}
function Table({headers,children,empty}){const has=Array.isArray(children)?children.length>0:Boolean(children);return <div className="overflow-x-auto"><table className="w-full text-left text-sm"><thead className="bg-gray-50 text-xs uppercase text-gray-500"><tr>{headers.map(value=><th key={value} className="px-5 py-3">{value}</th>)}</tr></thead><tbody>{has?children:<tr><td colSpan={headers.length} className="px-5 py-8 text-center text-gray-400">{empty}</td></tr>}</tbody></table></div>;}
function mask(value){return value.length<5?"••••":`${value.slice(0,2)}••••${value.slice(-4)}`;}
