import { BellRing, PhoneCall, UsersRound } from "lucide-react";
import { listEscalationPolicies, listNotificationGroups } from "../api/endpoints";
import TopBar from "../components/layout/TopBar";
import { AsyncSection } from "../components/ui/AsyncState";
import StatusPill from "../components/ui/StatusPill";
import { useApiResource } from "../hooks/useApiResource";

export default function VoiceAgentPage() {
  const policies = useApiResource(({ signal }) => listEscalationPolicies({ signal }), []);
  const groups = useApiResource(({ signal }) => listNotificationGroups({ signal }), []);
  return <div className="flex flex-col flex-1"><TopBar breadcrumbs={["Notifications", "Escalation"]} /><main className="flex-1 overflow-y-auto p-6 space-y-5"><div><h1 className="text-xl font-bold text-gray-900">Escalation & Voice Notifications</h1><p className="text-sm text-gray-500 mt-1">Live notification policies and groups used by the calling service.</p></div><div className="grid grid-cols-1 xl:grid-cols-2 gap-5"><Panel icon={BellRing} title="Escalation policies"><AsyncSection {...policies} onRetry={policies.refetch} isEmpty={(items) => items.length === 0} emptyTitle="No escalation policies configured"><div className="space-y-3">{(policies.data ?? []).map((policy) => <article key={policy.id} className="border border-gray-200 rounded-lg p-4"><div className="flex items-center justify-between gap-3"><h3 className="text-sm font-bold text-gray-900">{policy.name}</h3><StatusPill status={policy.enabled ? "ACTIVE" : "INACTIVE"} label={policy.enabled ? "Enabled" : "Disabled"} /></div><p className="text-xs text-gray-500 mt-2">{policy.steps?.length ?? 0} escalation step(s) · {policy.match?.severities?.join(", ") || "No severity match"}</p><div className="flex flex-wrap gap-1.5 mt-3">{(policy.steps ?? []).flatMap((step) => step.channels ?? []).filter((channel, index, all) => all.indexOf(channel) === index).map((channel) => <span key={channel} className="text-[10px] font-bold bg-blue-50 text-blue-700 px-2 py-1 rounded-full"><PhoneCall size={10} className="inline mr-1" />{channel}</span>)}</div></article>)}</div></AsyncSection></Panel><Panel icon={UsersRound} title="Notification groups"><AsyncSection {...groups} onRetry={groups.refetch} isEmpty={(items) => items.length === 0} emptyTitle="No notification groups configured"><ul className="divide-y divide-gray-100">{(groups.data ?? []).map((group) => <li key={group.id} className="py-3 flex items-center justify-between"><div><p className="text-sm font-semibold text-gray-900">{group.name}</p><p className="text-xs text-gray-500">{group.contactIds?.length ?? 0} contacts</p></div><StatusPill status={group.enabled ? "ACTIVE" : "INACTIVE"} label={group.enabled ? "Enabled" : "Disabled"} /></li>)}</ul></AsyncSection></Panel></div></main></div>;
}
function Panel({ icon: Icon, title, children }) { return <section className="bg-white rounded-xl border border-gray-200 shadow-sm p-5"><div className="flex items-center gap-2 mb-4"><Icon size={15} className="text-gray-400" /><h2 className="text-sm font-bold text-gray-900">{title}</h2></div>{children}</section>; }

